[project]
name = "whatsapp-oficial-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic-settings>=2.10.1",
    "pywa[fastapi]>=2.11.0",
]
